version: '3.1'

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: simple_bank